apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-cd-demo
  template:
    metadata:
      labels:
        app: argo-cd-demo
    spec:
      containers:
        - name: argo-cd-demo
          image: realsony/argo-cd-demo:0.0.1
          ports:
            - containerPort: 8080
